services:
  ################################################################################
  # All of the infrastructure services
  ################################################################################
  
  localstack:
    container_name: "cds-localstack-emulator"
    image: localstack/localstack:3.0.2
    ports:
      - '4566:4566' # LocalStack Gateway
    env_file:
      - 'dockerconfig/aws.env'
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3,sqs,sns,firehose
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/var/lib/localstack'
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: ['CMD', 'curl', 'http://cds-localstack-emulator:4566/health']
      interval: 5s
      start_period: 5s
      retries: 3

  redis:
    container_name: "cds-redis"
    image: redis:7.2.3-alpine3.18
    ports:
      - '6379:6379'
    restart: always

  ################################################################################

  cads-frontend:
      image: defradigital/cads-mis:latest
      container_name: cads-frontend
      working_dir: /app/cads-mis
      ports:
      - "5555:3000"
      depends_on:
        cads-backend:
          condition: service_started
        redis:
          condition: service_started
      command: npm run dev
      healthcheck:
        test: ["CMD", "curl", "http://localhost:5555/health"]
        interval: 5s
        timeout: 2s
        start_period: 20s
        retries: 10

  ################################################################################
  
  cads-backend:
    container_name: "cads_backend"
    working_dir: /app/cads-data-service
    image: defradigital/cads-data-service:latest
    ports:
      - '5555:5555'
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      PORT: 5555
      LOCALSTACK_ENDPOINT: http://cds-localstack-emulator:4566
    command: docker-compose -f docker-compose.yml -f docker-compose.override.yml up --build
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3000/health"]
      interval: 5s
      timeout: 2s
      retries: 30
  ################################################################################
