services:
  ################################################################################
  # All of the infrastructure services
  ################################################################################

  cads-frontend:
      image: defradigital/cads-mis:${CADS_FRONTEND:-latest}
      container_name: cads-frontend
      depends_on:
        cads-backend:
          condition: service_started
      healthcheck:
        test: ["CMD", "curl", "http://localhost:5555/health"]
        interval: 5s
        timeout: 2s
        start_period: 20s
        retries: 10

  ################################################################################
  
  cads-backend:
    container_name: "cads_backend"
    platform: linux
    image: defradigital/cads-data-service:${CADS_BACKEND:-latest}
    ports:
      - '5555:5555'
  ################################################################################
