services:
  journey-tests:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENVIRONMENT: docker
      PROFILE: ""
      RUN_ID: "docker"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS:-false}"
      AUTH_BASIC_TOKEN: "${AUTH_BASIC_TOKEN}"
    env_file:
      - ./compose/aws.env
      - ./compose/postgres.env
      - ./compose/frontend.env
      - .env.docker
    depends_on: []
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/allure-report
      - ./playwright-report:/app/playwright-report
    networks:
      - cads-network

networks:
  cads-network:
    external: true
  default:
    external: true
