services:
  journey-tests:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENVIRONMENT: docker
      PROFILE: ""
      RUN_ID: "docker"
    env_file:
      - ./compose/aws.env
      - ./compose/postgres.env
      - ./compose/frontend.env
      - .env.docker
    depends_on: []
    networks:
      - cads-tools
    # No volumes — use the image exactly as CDP will
    # volumes:
    #   - .:/app

networks:
  cads-tools:
    external: true
