name: Run Journey Tests

on:
  workflow_dispatch:
    permissions:
      contents: read

inputs:
  cads-frontend:
    required: false
    type: string
  cads-backend:
    required: false
    type: string
  test:
    description: "Choose Test Suite"
    type: choice
    required: true
    options:
      - API
      - UI
  tag:
    description: "Choose Test Group"
    type: choice
    required: true
    options:
      - Smoke
      - E2E    

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: DEFRA/cads-journey-tests

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
    - name: Setup the tests
      run: npm i
      shell: bash

    - name: Start docker compose
      shell: bash
      run: |
          docker compose -f compose.common.yml -f compose.ci.yml up --wait-timeout 300 -d --quiet-pull
          docker ps --format "table {{.Names}}\t{{.Ports}}"
    - name: Backend logs + health probe
      shell: bash
      run: |
        set -euxo pipefail
        echo "=== Try HTTP ==="
        curl -v --max-time 5 http://127.0.0.1:5555/ || true

        echo "=== Try HTTPS (ignore cert) ==="
        curl -vk --max-time 5 https://127.0.0.1:5555/ || true

        echo "=== Backend logs ==="
        docker compose -f compose.common.yml -f compose.ci.yml logs --no-color --tail=300 cads-backend || true
    - name: Run the tests
      shell: bash
      run: |
        npx playwright install --with-deps

        TEST_INPUT="${{ inputs.test }}"
        TAG_INPUT="${{ inputs.tag }}"

        FILTER=""

        if [[ -n "$TEST_INPUT" ]]; then
          FILTER="$TEST_INPUT"
        fi

        if [[ -n "$TAG_INPUT" ]]; then
          if [[ -n "$FILTER" ]]; then
            FILTER="$FILTER|$TAG_INPUT"
          else
            FILTER="$TAG_INPUT"
          fi
        fi

        if [[ -z "$FILTER" ]]; then
          echo "No filters provided. Running all tests..."
          npx playwright test
        else
          echo "Running filtered tests with grep: $FILTER"
          npx playwright test --grep="$FILTER"
        fi
    - name: debug
      if: always()
      run: |
        docker compose logs > logs.txt
        docker ps
      shell: bash
    - name: Post Slack Report
      shell: bash
      run: |
        BUILD_URL="Build URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
        node post-slack-report.ts
    - name: Upload playwright report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: ./playwright-report/html
    - name: Upload docker compose logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: docker-compose-logs
        path: ./logs.txt
