name: Run Journey Tests

permissions:
  checks: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      cads-frontend:
        description: "CADS frontend image tag"
        required: false
        type: string
        default: latest
      cads-backend:
        description: "CADS backend image tag"
        required: false
        type: string
        default: latest
      cads-environment:
        description: "Target environment"
        required: true
        type: choice
        default: docker
        options:
          - local
          - docker
          - dev
          - test
      test:
        description: "Choose Test Suite"
        type: choice
        required: false
        default: ''
        options:
          - ''
          - API
          - UI
      tag:
        description: "Choose Test Group"
        type: choice
        required: false
        default: ''
        options:
          - ''
          - Smoke
          - E2E
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
  workflow_call:
    inputs:
      cads-frontend:
        required: false
        type: string
        default: latest
      cads-backend:
        required: false
        type: string
        default: latest
      cads-environment:
        required: false
        type: string
        default: docker
      test:
        required: false
        type: string
        default: ''
      tag:
        required: false
        type: string
        default: ''
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
jobs:
  build:
    name: Run Journey Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check Slack secret is present
        run: echo "Has SLACK_WEBHOOK_URL secret: ${{ secrets.SLACK_WEBHOOK_URL != '' }}"
      - uses: ./run-journey-tests
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
