name: Run Journey Tests

permissions:
  checks: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      cads-frontend:
        description: "CADS frontend image tag"
        required: false
        type: string
      cads-backend:
        description: "CADS backend image tag"
        required: false
        type: string
      cads-environment:
        description: "Target environment"
        required: true
        type: choice
        default: docker
        options:
          - local
          - docker
          - dev
          - test
      test:
        description: "Choose Test Suite"
        type: choice
        required: false
        options:
          - API
          - UI
      tag:
        description: "Choose Test Group"
        type: choice
        required: false
        options:
          - Smoke
          - E2E
  workflow_call:
    inputs:
      cads-frontend:
        required: false
        type: string
      cads-backend:
        required: false
        type: string
      cads-environment:
        required: false
        type: string
        default: docker
      test:
        required: false
        type: string
      tag:
        required: false
        type: string
jobs:
  build:
    name: Run Journey Tests
    runs-on: ubuntu-latest
    steps:
     - name: Start docker compose
       shell: bash
       run: |
        echo "Environment1: ${{ github.inputs.cads-environment }}"
      - uses: DEFRA/cads-journey-tests/run-journey-tests@main
        with:
          cads-environment: ${{ github.event.inputs.cads-environment }}
          test: ${{ github.event.inputs.test }}
          tag: ${{ github.event.inputs.tag }}
